# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            rdi-client-java
tagline:          A client library for integrating with Metamarkets real-time ingestion API
url:              https://metamx.github.io/rdi-client-java/
author:
  name:           Metamarkets
  url:            https://twitter.com/metamarkets
  email:          contact@metamarkets.com

# Custom vars
version:          0.0.1-SNAPSHOT
github:
  repo:           https://github.com/metamx/rdi-client-java
